services:
  - name: auth-service
    env:
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        from_secret: mongodb_uri
      - key: JWT_SECRET
        from_secret: jwt_secret
      - key: JWT_EXPIRE
        value: "24h"
    startCommand: npm start
